2017-07-27 15:13:42,621:621.140003204 - ubuntu_sso.utils.translation - WARNING - Translations not found, using null translator.
2017-07-27 15:13:43,012:12.2590065002 - ubuntu_sso.main - INFO - Setting up Ubuntu SSO service.
2017-07-27 15:13:43,304:304.933071136 - ubuntu_sso.main - INFO - Ubuntu SSO service started.
2017-07-27 15:13:43,305:305.053949356 - ubuntu_sso.account - INFO - Creating a new SSO access layer for service url u'https://login.ubuntu.com/api/1.0/'
2017-07-27 15:13:43,454:454.968929291 - ubuntu_sso.credentials - ERROR - find_credentials (app_name: Ubuntu One): Problem while getting credentials from the keyring.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ubuntu-sso-client/ubuntu_sso/credentials.py", line 104, in inner
    result = yield f(self, *a, **kw)
DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.freedesktop.secrets exited with status 1
2017-07-27 15:13:43,473:473.069906235 - ubuntu_sso.main - ERROR - 'CredentialsManagement': emitting 'CredentialsError' with args (dbus.String(u'Ubuntu One'), DBusException('Process org.freedesktop.secrets exited with status 1',)) and kwargs {}
2017-07-27 15:13:53,494:494.363069534 - ubuntu_sso.main - INFO - Shutting down, calling <function shutdown_func at 0x7fe8ed267c80>.
2017-07-29 13:53:26,287:287.048101425 - ubuntu_sso.utils.translation - WARNING - Translations not found, using null translator.
2017-07-29 13:53:26,597:597.446918488 - ubuntu_sso.main - INFO - Setting up Ubuntu SSO service.
2017-07-29 13:53:26,962:962.608098984 - ubuntu_sso.main - INFO - Ubuntu SSO service started.
2017-07-29 13:53:26,962:962.738990784 - ubuntu_sso.account - INFO - Creating a new SSO access layer for service url u'https://login.ubuntu.com/api/1.0/'
2017-07-29 13:53:27,074:74.5511054993 - ubuntu_sso.credentials - ERROR - find_credentials (app_name: Ubuntu One): Problem while getting credentials from the keyring.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ubuntu-sso-client/ubuntu_sso/credentials.py", line 104, in inner
    result = yield f(self, *a, **kw)
DBusException: org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.freedesktop.secrets exited with status 1
2017-07-29 13:53:27,080:80.9400081635 - ubuntu_sso.main - ERROR - 'CredentialsManagement': emitting 'CredentialsError' with args (dbus.String(u'Ubuntu One'), DBusException('Process org.freedesktop.secrets exited with status 1',)) and kwargs {}
2017-07-29 13:53:37,104:104.57110405 - ubuntu_sso.main - INFO - Shutting down, calling <function shutdown_func at 0x7fa106ecac80>.
